"""empty message

Revision ID: 330b5a02dd40
Revises: 7cecea9733f2
Create Date: 2024-09-09 21:09:33.839867

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '330b5a02dd40'
down_revision = '7cecea9733f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agendamento', schema=None) as batch_op:
        batch_op.drop_index('data')
        batch_op.drop_index('email')
        batch_op.drop_index('especialidade')
        batch_op.drop_index('hora')
        batch_op.drop_index('nome')
        batch_op.drop_index('sexo')

    op.drop_table('agendamento')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agendamento',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nome', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('email', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('especialidade', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('sexo', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('data', mysql.DATETIME(), nullable=True),
    sa.Column('hora', mysql.TIME(), nullable=True),
    sa.Column('agendamento_form', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('descricao', mysql.VARCHAR(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('agendamento', schema=None) as batch_op:
        batch_op.create_index('sexo', ['sexo'], unique=True)
        batch_op.create_index('nome', ['nome'], unique=True)
        batch_op.create_index('hora', ['hora'], unique=True)
        batch_op.create_index('especialidade', ['especialidade'], unique=True)
        batch_op.create_index('email', ['email'], unique=True)
        batch_op.create_index('data', ['data'], unique=True)

    # ### end Alembic commands ###
